# Institution Data Sources Configuration
# Configure scraping strategies for each institution

institutions:
  - id: unilag
    name: University of Lagos
    url: https://www.unilag.edu.ng
    type: federal_university
    state: Lagos
    scrape_config:
      programs_url: https://www.unilag.edu.ng/programmes
      admissions_url: https://www.unilag.edu.ng/admissions
      schedule: daily  # daily, weekly, monthly
      requires_js: false

  - id: ui
    name: University of Ibadan
    url: https://www.ui.edu.ng
    type: federal_university
    state: Oyo
    scrape_config:
      programs_url: https://www.ui.edu.ng/programmes
      admissions_url: https://www.ui.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: oau
    name: Obafemi Awolowo University
    url: https://oauife.edu.ng
    type: federal_university
    state: Osun
    scrape_config:
      programs_url: https://oauife.edu.ng/programmes
      admissions_url: https://oauife.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: abu
    name: Ahmadu Bello University
    url: https://abu.edu.ng
    type: federal_university
    state: Kaduna
    scrape_config:
      programs_url: https://abu.edu.ng/programmes
      admissions_url: https://abu.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: unn
    name: University of Nigeria, Nsukka
    url: https://unn.edu.ng
    type: federal_university
    state: Enugu
    scrape_config:
      programs_url: https://unn.edu.ng/programmes
      admissions_url: https://unn.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: uniben
    name: University of Benin
    url: https://uniben.edu
    type: federal_university
    state: Edo
    scrape_config:
      programs_url: https://uniben.edu/programmes
      admissions_url: https://uniben.edu/admissions
      schedule: daily
      requires_js: false

  - id: unilorin
    name: University of Ilorin
    url: https://unilorin.edu.ng
    type: federal_university
    state: Kwara
    scrape_config:
      programs_url: https://unilorin.edu.ng/programmes
      admissions_url: https://unilorin.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: buk
    name: Bayero University Kano
    url: https://buk.edu.ng
    type: federal_university
    state: Kano
    scrape_config:
      programs_url: https://buk.edu.ng/programmes
      admissions_url: https://buk.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: futa
    name: Federal University of Technology, Akure
    url: https://futa.edu.ng
    type: federal_university
    state: Ondo
    scrape_config:
      programs_url: https://futa.edu.ng/programmes
      admissions_url: https://futa.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: futo
    name: Federal University of Technology, Owerri
    url: https://futo.edu.ng
    type: federal_university
    state: Imo
    scrape_config:
      programs_url: https://futo.edu.ng/programmes
      admissions_url: https://futo.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: uniport
    name: University of Port Harcourt
    url: https://uniport.edu.ng
    type: federal_university
    state: Rivers
    scrape_config:
      programs_url: https://uniport.edu.ng/programmes
      admissions_url: https://uniport.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: lasu
    name: Lagos State University
    url: https://lasu.edu.ng
    type: state_university
    state: Lagos
    scrape_config:
      programs_url: https://lasu.edu.ng/programmes
      admissions_url: https://lasu.edu.ng/admissions
      schedule: daily
      requires_js: false

  - id: obong
    name: Obong University
    url: https://obonguniversity.edu.ng
    type: private_university
    state: Akwa Ibom
    scrape_config:
      programs_url: https://obonguniversity.edu.ng/programmes
      admissions_url: https://obonguniversity.edu.ng/admissions
      schedule: daily
      requires_js: false

  # Add more institutions here
  # Template:
  # - id: institution_slug
  #   name: Institution Name
  #   url: https://example.com
  #   type: federal_university|state_university|private_university|polytechnic
  #   state: State Name
  #   scrape_config:
  #     programs_url: URL to programs page
  #     admissions_url: URL to admissions page
  #     schedule: daily|weekly|monthly
  #     requires_js: true|false
